export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    REMOVED_SELECTED_PRODUCTS:"REMOVED_SELECTED_PRODUCTS",
}